### ISSUE TITLE
Jenkins job configurations cannot be saved in the UI after update to 2.277.3

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/cookbook-ros-buildfarm#90]
Major changes since the last LTS have made it so that saving the configuration manually no longer works due to incompatibilities with the new div-based configuration layout and older plugins.

The official list of plugins with issues is on [this JIRA dashboard](https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=20741).

There are several plugins that we're using with some jobs.

The official recommendation from [this Jenkins 2.277.1 upgrade guide](https://www.jenkins.io/doc/upgrade-guide/2.277/#upgrading-to-jenkins-lts-2-277-1) is to follow [these steps for identifying broken plugins](https://www.jenkins.io/doc/developer/views/table-to-div-migration/#identifying-the-broken-plugin). They also advocate a blanket update of all plugins which is always risky for us.

This is kind of a downer, especially because we're "forced" to take these breaking changes in order to receive security updates but we can still operate the buildfarm under these conditions because the issue does not affect the API used by ros_buildfarm to update configurations via XML.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/upgrade-to-jenkins-2-277-3-causing-job-failures-across-ros-build-farms/20013/4

**Comment by nuclearsandwich** [comment]
This issue was resolved by #93.
